[tool.poetry]
name = "ai-rpg"
version = "0.1.0"
description = "A D&D game powered by AI"
authors = ["Your Name <your.email@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "0.95.2"
uvicorn = "0.22.0"
requests = "2.31.0"
pydantic = "1.10.8"

[tool.poetry.dev-dependencies]
pytest = "7.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
